name: CI - Lint

on:
  workflow_call:
    inputs:
      language:
        required: false
        type: string
      version:
        required: false
        type: string
      framework:
        required: true
        type: string
      active:
        required: false
        default: true
        type: boolean

jobs:
  ruby-rubocop:
    if: ${{ inputs.active && inputs.language == 'ruby' && inputs.framework == 'rubocop' }}
    name: Ruby Rubocop
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running ruby/rubocop"

  python-pylint:
    if: ${{ inputs.active && inputs.language == 'python' && inputs.framework == 'pylint' }}
    name: Python PyLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.version }}
          cache: pipenv
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install
      - name: Lint check
        run: pylint **/*.py

  javascript-eslint:
    if: ${{ inputs.active && inputs.language == 'javascript' && inputs.framework == 'eslint' }}
    name: JavaScript ESLint
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running javascript/eslint"
