name: Python CI Pipeline

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      lint-active:
        required: false
        default: true
        type: boolean
      test-active:
        required: false
        default: true
        type: boolean

jobs:
  ci-lint:
    name: Lint
    uses: ddalpian/workflow-templates/.github/workflows/python-ci-pylint.yaml@master
    with:
      python-version: ${{ inputs.python-version }}
      active: ${{ inputs.lint-active }}

  ci-test:
    name: Test
    uses: ddalpian/workflow-templates/.github/workflows/python-ci-pytest.yaml@master
    with:
      python-version: ${{ inputs.python-version }}
      active: ${{ inputs.test-active }}
